### PR TITLE
Added Blueprint and C++ function execution and tutorials

### PR DESCRIPTION
**Pull request by FeikoJoosten**
Hi, I've Extended your plugin a while back to have the ability to directly run Blueprint and C++ functions using dialogues. This extension was used during the development of [Bone Voyage](https://store.steampowered.com/app/1058370/Bone_Voyage/) and has heavily utilized throughout the development phase. 

It allowed us to reuse the same functions without having to rely on the `OnDialogueEvent` and `CheckConditions` callbacks. 

See the [Examples](Examples/README.md) for a tutorial on how to utilize these features.

I figured you guys could possibly be interested in this feature, so feel free to use it as you like.

Let me know if something is unclear, or should be changed!

### CODE REVIEW

**Comment by vampy** [comment]
Hi, thanks for the PR and lettings us know unfortunately this PR is in the wrong place and branch :(. We only use github as a mirror, main repo is on gitlab https://gitlab.com/NotYetGames/DlgSystem and `4.22` is the default branch, where I  recently modified a lot of stuff and will probably merge to the other branches in the near future.

If you don't have time to move your modifications there, I will probably merge your changes manually in the next month or so.

Thanks again.

**Comment by FeikoJoosten** [comment]
Sorry for pushing this to the incorrect repo. I wanted to use this PR (and the branch itself) as portfolio reference. Since all of my previous work is on Github, this was easier for me. I'll try and see if I'll have some time to push these changes to the main branch on Gitlab. The thing that'll take the longest will most likely be the installing of `4.22`. The PR itself aint that big, and should easily be convertible to Gitlab. 

If you don't see a PR on Gitlab anytime soon, I won't have any time for it and I'll leave the rest up to you.

I hope the PR itself will be useful to you guys, it was at least quite useful to us hehe.

**Comment by FeikoJoosten** [comment]
@vampy Hi, I was wondering if you've already had the time to merge this manually? :)

**Comment by vampy** [comment]
Ups totally forgot about this, sorry.
We are currently kinda timed constraint because of the release of our game [WarriOrb](https://www.warriorb.com/), but I will see what I can do.

I created an issue [here ](https://gitlab.com/NotYetGames/DlgSystem/-/issues/26) to not forget about this.
And because some core things changed quite a bit and I have some nitpicks with the current PR code I will have to do a manual merge of each file 😅 .

But thanks again to the changes, we don't have that many people who contribute back to our plugin.

**Comment by FeikoJoosten** [comment]
no problem, I completely forgot to give the merge on the main branch a try as well. 😓
I hope your release will go well! 

Let me know if there's anything unclear about the PR and I'll do my best to clear things up. These changes really helped speed up the development of Bone Voyage as we could simple create functions and use those over and over without having to dive into the `OnDialogueEvent` and `CheckConditions` logic. I figured these changes would make a nice addition to a free plugin 😉.

**Pull request closed without merging**
